spring:
  redis:
    host: 192.168.1.11
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
      
  rabbitmq:
    host: 192.168.1.11
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
        
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.11:8761/eureka